language: node_js
node_js: "8"
services: mongodb

env:
  global:
    - NODE_ENV=test

install:
  yarn install

cache: 
  yarn

before_script:
  - sleep 2

script:
  - yarn run start:server &
  - sleep 2
  - yarn run test:server