language: node_js
node_js: "8"
services: mongodb

env:
  global:
    - NODE_ENV=test

install:
  yarn install

cache: 
  yarn

before_script:
  - sleep 2
  - mongo persianTest --eval 'db.createCollection("users")'
  # had to escape the following line in a weird way because of nested objects and quotes
  - "mongo persianTest --eval 'db.users.insert({username: \"admin\", email: \"admin@test.com\", role: \"admin\", password: \"$2a$10$tcHz5Nl8IHvxhj7zdxhWR.jZPRO52Ftqr5PfGuzBuZdRJX2NX1KgW\"})'"

script:
  - yarn run start:server &
  - sleep 2
  - yarn run test:server

after_script:
  --mongo persianTest --eval 'db.dropDatabase()'