export const SET_SCORE_PENDING = 'SET_SCORE_PENDING';
export const SET_SCORE_SUCCESS = 'SET_SCORE_SUCCESS';
export const SET_SCORE_ERROR = 'SET_SCORE_ERROR';

export const FETCH_SCORES_PENDING = 'FETCH_SCORES_PENDING';
export const FETCH_SCORES_SUCCESS = 'FETCH_SCORES_SUCCESS';
export const FETCH_SCORES_ERROR = 'FETCH_SCORES_ERROR';
