export const FETCH_WORDS_PENDING = 'FETCH_WORDS_PENDING';
export const FETCH_WORDS_SUCCESS = 'FETCH_WORDS_SUCCESS';
export const FETCH_WORDS_ERROR = 'FETCH_WORDS_ERROR';

export const ADD_WORD_PENDING = 'ADD_WORD_PENDING';
export const ADD_WORD_SUCCESS = 'ADD_WORD_SUCCESS';
export const ADD_WORD_ERROR = 'ADD_WORD_ERROR';

export const BULK_ADD_WORDS_PENDING = 'BULK_ADD_WORDS_PENDING';
export const BULK_ADD_WORDS_SUCCESS = 'BULK_ADD_WORDS_SUCCESS';
export const BULK_ADD_WORDS_ERROR = 'BULK_ADD_WORDS_ERROR';

export const DELETE_WORD_PENDING = 'DELETE_WORD_PENDING';
export const DELETE_WORD_SUCCESS = 'DELETE_WORD_SUCCESS';
export const DELETE_WORD_ERROR = 'DELETE_WORD_ERROR';

export const EDIT_WORD_PENDING = 'EDIT_WORD_PENDING';
export const EDIT_WORD_SUCCESS = 'EDIT_WORD_SUCCESS';
export const EDIT_WORD_ERROR = 'EDIT_WORD_ERROR';
