export const SELECT_WORD = 'SELECT_WORD';
export const SELF_EVAL = 'SELF_EVAL';

export const MARK_CORRECT = 'MARK_CORRECT';
export const MARK_WRONG = 'MARK_WRONG';

export const SHOW_QUIZ_OPTIONS = 'SHOW_QUIZ_OPTIONS';
export const UPDATE_QUIZ_OPTIONS = 'UPDATE_QUIZ_OPTIONS';
export const REVERT_QUIZ_OPTIONS = 'REVERT_QUIZ_OPTIONS';

export const START_EDITING_WORD = 'START_EDITING_WORD';
export const QUIZ_EDIT_WORD = 'QUIZ_EDIT_WORD';
export const REVERT_EDIT_WORD = 'REVERT_EDIT_WORD';
