export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT = 'LOGOUT';

export const AUTH_ERROR = 'AUTH_ERROR';
export const SHOW_LOGIN_DIALOG = 'SHOW_LOGIN_DIALOG';
export const SHOW_CREATE_ACCOUNT_DIALOG = 'SHOW_CREATE_ACCOUNT_DIALOG';
export const SHOW_FORGOT_DIALOG = 'SHOW_FORGOT_DIALOG';
export const HIDE_AUTH_DIALOG = 'HIDE_AUTH_DIALOG';

export const CREATE_ACCOUNT_PENDING = 'CREATE_ACCOUNT_PENDING';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_ERROR = 'CREATE_ACCOUNT_ERROR';
