export const FETCH_WORDS = 'FETCH_WORDS';
export const FETCH_WORDS_PENDING = 'FETCH_WORDS_PENDING';
export const FETCH_WORDS_SUCCESS = 'FETCH_WORDS_SUCCESS';
export const FETCH_WORDS_ERROR = 'FETCH_WORDS_ERROR';
export const ADD_WORD = 'ADD_WORD';
export const ADD_WORD_PENDING = 'ADD_WORD_PENDING';
export const ADD_WORD_SUCCESS = 'ADD_WORD_SUCCESS';
export const ADD_WORD_ERROR = 'ADD_WORD_ERROR';
export const DELETE_WORD = 'DELETE_WORD';
export const DELETE_WORD_PENDING = 'DELETE_WORD_PENDING';
export const DELETE_WORD_SUCCESS = 'DELETE_WORD_SUCCESS';
export const DELETE_WORD_ERROR = 'DELETE_WORD_ERROR';
export const EDIT_WORD = 'EDIT_WORD';
export const EDIT_WORD_PENDING = 'EDIT_WORD_PENDING';
export const EDIT_WORD_SUCCESS = 'EDIT_WORD_SUCCESS';
export const EDIT_WORD_ERROR = 'EDIT_WORD_ERROR';

export const SELECT_WORD = 'SELECT_WORD';
export const MARK_CORRECT = 'MARK_CORRECT';
export const MARK_CORRECT_SUCCESS = 'MARK_CORRECT_SUCCESS';
export const MARK_WRONG = 'MARK_WRONG';
export const MARK_WRONG_SUCCESS = 'MARK_WRONG_SUCCESS';

export const QUIZ_PENDING = 'QUIZ_PENDING';
export const QUIZ_ERROR = 'QUIZ_ERROR';
