export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_ERROR = 'CREATE_ACCOUNT_ERROR';

export const FETCH_WORDS_PENDING = 'FETCH_WORDS_PENDING';
export const FETCH_WORDS_SUCCESS = 'FETCH_WORDS_SUCCESS';
export const FETCH_WORDS_ERROR = 'FETCH_WORDS_ERROR';

export const ADD_WORD_PENDING = 'ADD_WORD_PENDING';
export const ADD_WORD_SUCCESS = 'ADD_WORD_SUCCESS';
export const ADD_WORD_ERROR = 'ADD_WORD_ERROR';

export const BULK_ADD_WORDS_PENDING = 'BULK_ADD_WORDS_PENDING';
export const BULK_ADD_WORDS_SUCCESS = 'BULK_ADD_WORDS_SUCCESS';
export const BULK_ADD_WORDS_ERROR = 'BULK_ADD_WORDS_ERROR';

export const DELETE_WORD_PENDING = 'DELETE_WORD_PENDING';
export const DELETE_WORD_SUCCESS = 'DELETE_WORD_SUCCESS';
export const DELETE_WORD_ERROR = 'DELETE_WORD_ERROR';

export const EDIT_WORD_PENDING = 'EDIT_WORD_PENDING';
export const EDIT_WORD_SUCCESS = 'EDIT_WORD_SUCCESS';
export const EDIT_WORD_ERROR = 'EDIT_WORD_ERROR';

export const SELECT_WORD = 'SELECT_WORD';
export const SUBMIT_WORD = 'SUBMIT_WORD';

export const SHOW_QUIZ_OPTIONS = 'SHOW_QUIZ_OPTIONS';
export const UPDATE_QUIZ_OPTIONS = 'UPDATE_QUIZ_OPTIONS';

export const QUIZ_PENDING = 'QUIZ_PENDING';
export const QUIZ_ERROR = 'QUIZ_ERROR';
