export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT = 'LOGOUT';

export const AUTH_ERROR = 'AUTH_ERROR';
export const SHOW_LOGIN_DIALOG = 'SHOW_LOGIN_DIALOG';
export const SHOW_CREATE_ACCOUNT_DIALOG = 'SHOW_CREATE_ACCOUNT_DIALOG';
export const SHOW_FORGOT_DIALOG = 'SHOW_FORGOT_DIALOG';
export const HIDE_AUTH_DIALOG = 'HIDE_AUTH_DIALOG';

export const CREATE_ACCOUNT_PENDING = 'CREATE_ACCOUNT_PENDING';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_ERROR = 'CREATE_ACCOUNT_ERROR';

export const FETCH_WORDS_PENDING = 'FETCH_WORDS_PENDING';
export const FETCH_WORDS_SUCCESS = 'FETCH_WORDS_SUCCESS';
export const FETCH_WORDS_ERROR = 'FETCH_WORDS_ERROR';

export const ADD_WORD_PENDING = 'ADD_WORD_PENDING';
export const ADD_WORD_SUCCESS = 'ADD_WORD_SUCCESS';
export const ADD_WORD_ERROR = 'ADD_WORD_ERROR';

export const BULK_ADD_WORDS_PENDING = 'BULK_ADD_WORDS_PENDING';
export const BULK_ADD_WORDS_SUCCESS = 'BULK_ADD_WORDS_SUCCESS';
export const BULK_ADD_WORDS_ERROR = 'BULK_ADD_WORDS_ERROR';

export const DELETE_WORD_PENDING = 'DELETE_WORD_PENDING';
export const DELETE_WORD_SUCCESS = 'DELETE_WORD_SUCCESS';
export const DELETE_WORD_ERROR = 'DELETE_WORD_ERROR';

export const EDIT_WORD_PENDING = 'EDIT_WORD_PENDING';
export const EDIT_WORD_SUCCESS = 'EDIT_WORD_SUCCESS';
export const EDIT_WORD_ERROR = 'EDIT_WORD_ERROR';

export const SELECT_WORD = 'SELECT_WORD';
export const SELF_EVAL = 'SELF_EVAL';

export const MARK_CORRECT_PENDING = 'MARK_CORRECT_PENDING';
export const MARK_CORRECT_SUCCESS = 'MARK_CORRECT_SUCCESS';
export const MARK_CORRECT_ERROR = 'MARK_CORRECT_ERROR';

export const MARK_WRONG_PENDING = 'MARK_WRONG_PENDING';
export const MARK_WRONG_SUCCESS = 'MARK_WRONG_SUCCESS';
export const MARK_WRONG_ERROR = 'MARK_WRONG_ERROR';

export const SHOW_QUIZ_OPTIONS = 'SHOW_QUIZ_OPTIONS';
export const UPDATE_QUIZ_OPTIONS = 'UPDATE_QUIZ_OPTIONS';
export const REVERT_QUIZ_OPTIONS = 'REVERT_QUIZ_OPTIONS';

export const START_EDITING_WORD = 'START_EDITING_WORD';
export const QUIZ_EDIT_WORD = 'QUIZ_EDIT_WORD';
export const REVERT_EDIT_WORD = 'REVERT_EDIT_WORD';
