export const FETCH_LEADERBOARD_PENDING = 'FETCH_LEADERBOARD_PENDING';
export const FETCH_LEADERBOARD_SUCCESS = 'FETCH_LEADERBOARD_SUCCESS';
export const FETCH_LEADERBOARD_ERROR = 'FETCH_LEADERBOARD_ERROR';
